# Generated by Django 2.2.6 on 2019-10-10 18:36

import django.contrib.auth.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='login_hash',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='qr_hash',
            field=models.UUIDField(default=uuid.uuid1),
        ),
        migrations.AddField(
            model_name='user',
            name='sat_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sat_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sat_lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sun_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sun_lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='hello', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
