# Generated by Django 2.2.6 on 2019-10-10 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191010_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_confirmation', models.UUIDField(default=uuid.uuid1)),
                ('subject', models.CharField(default='', max_length=1000)),
                ('message', models.CharField(default='', max_length=20000)),
                ('action', models.CharField(default='', max_length=1000)),
                ('redirect_url', models.CharField(default='', max_length=1000)),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
