# Generated by Django 2.2.6 on 2019-10-11 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tshirt', models.CharField(default='', max_length=1000)),
                ('dietary', models.CharField(default='', max_length=1000)),
                ('phone', models.CharField(default='', max_length=100)),
                ('github', models.CharField(default='', max_length=1000)),
                ('notes', models.CharField(default='', max_length=10000)),
                ('resume_file_name', models.CharField(default='', max_length=10000)),
                ('confirmed', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
            ],
        ),
    ]
