# Generated by Django 2.2.6 on 2019-10-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Confirmation',
        ),
    ]
