# Generated by Django 2.2.6 on 2019-10-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191022_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_judge',
            field=models.BooleanField(default=False),
        ),
    ]
