# Generated by Django 2.2.8 on 2020-01-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191217_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slack_ts',
            field=models.CharField(default='', max_length=40),
        ),
    ]
