# Generated by Django 2.2.4 on 2021-01-08 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_ticket_slack_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackerTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Team', max_length=100)),
                ('unique_code', models.CharField(default='8CTJsLjG', max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judging.Organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.HackerTeam'),
        ),
    ]
