# Generated by Django 2.2.4 on 2021-01-08 04:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210108_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackerteam',
            name='unique_code',
            field=models.CharField(default=users.models.random_string, max_length=100, unique=True),
        ),
    ]
