# Generated by Django 2.2.4 on 2021-01-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210108_0404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HackerTeam',
            new_name='PuzzleTeam',
        ),
    ]
