# Generated by Django 2.2.4 on 2021-01-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210108_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('regex_answer', models.CharField(max_length=1000)),
                ('max_points', models.IntegerField()),
            ],
        ),
    ]
