# Generated by Django 2.2.4 on 2021-01-08 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_puzzle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_recent_solution', models.CharField(max_length=1000)),
                ('locked', models.BooleanField(default=False)),
                ('num_attempts', models.IntegerField()),
                ('points_earned', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('puzzle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='users.Puzzle')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='users.PuzzleTeam')),
            ],
        ),
    ]
