# Generated by Django 2.2.4 on 2021-01-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_puzzlesolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlesolution',
            name='previous_attempts',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
