# Generated by Django 2.2.13 on 2021-02-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_puzzlesolution_previous_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raffle_tickets',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
    ]
