# Generated by Django 2.2.6 on 2019-10-11 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_auto_20191011_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(default='', max_length=1000)),
                ('school', models.CharField(default='', max_length=1000)),
                ('grad_year', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=100)),
                ('race', models.CharField(default='', max_length=100)),
                ('describe', models.CharField(default='', max_length=200)),
                ('why', models.CharField(default='', max_length=1800)),
                ('major', models.CharField(default='', max_length=1000)),
                ('birthday', models.CharField(default='', max_length=1000)),
                ('mlh_rules', models.BooleanField(default=False)),
                ('hackathons', models.IntegerField(default=0)),
                ('app_complete', models.BooleanField(default=False)),
                ('travel', models.BooleanField(default=False)),
                ('where_from', models.CharField(default='', max_length=1000)),
                ('travel_method', models.CharField(default='', max_length=1000)),
                ('miles', models.CharField(default='', max_length=100)),
                ('cost', models.CharField(default='', max_length=1000)),
                ('accepted', models.BooleanField(default=False)),
                ('waitlisted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tshirt', models.CharField(default='', max_length=1000)),
                ('dietary', models.CharField(default='', max_length=1000)),
                ('phone', models.CharField(default='', max_length=100)),
                ('github', models.CharField(default='', max_length=1000)),
                ('notes', models.CharField(default='', max_length=10000)),
                ('resume_file_name', models.CharField(default='', max_length=10000)),
                ('confirmed', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
            ],
        ),
    ]
