# Generated by Django 2.2.8 on 2020-01-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20191217_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='carrier',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
