# Generated by Django 2.2.8 on 2020-01-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_confirmation_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='mlh_consent',
            field=models.BooleanField(default=False),
        ),
    ]
