# Generated by Django 2.2.8 on 2020-04-13 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_ticket_slack_ts'),
        ('applications', '0004_application_mlh_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TshirtOrder',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tshirt', models.CharField(default='', max_length=10)),
                ('street_address', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(default='', max_length=10)),
                ('devpost_url', models.URLField()),
                ('devpost_email', models.EmailField(default='', max_length=100)),
            ],
        ),
    ]
