# Generated by Django 2.2.8 on 2020-04-13 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_tshirtorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirtorder',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tshirt_order', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
