# Generated by Django 2.2.8 on 2020-04-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20200413_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirtorder',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
