# Generated by Django 2.2.13 on 2021-02-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_tshirtorder_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='referrer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
