# Generated by Django 2.2.13 on 2021-02-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='referrer_locked',
            field=models.BooleanField(default=False),
        ),
    ]
