# Generated by Django 4.1.3 on 2022-12-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_confirmation_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dietary_restriction',
            field=models.CharField(default='', max_length=100),
        ),
    ]
