# Generated by Django 2.2.6 on 2019-10-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_submission_deadline', models.DateTimeField(auto_now_add=True)),
                ('application_confirmation_deadline', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
