# Generated by Django 4.1.3 on 2022-12-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_settings_application_confirmation_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='application_confirmation_deadline',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='application_submission_deadline',
        ),
    ]
