import secret

DATABASE_URL = secret.DATABASE_URL
SECRET_KEY = secret.SECRET_KEY
SQLALCHEMY_TRACK_MODIFICATIONS = secret.SQLALCHEMY_TRACK_MODIFICATIONS
APP_SETTINGS = secret.APP_SETTINGS
ADMIN_USERNAME = secret.ADMIN_USERNAME
ADMIN_PASSWORD = secret.ADMIN_PASSWORD
EVENT_NAME = "HooHacks"
