# Generated by Django 2.2.6 on 2019-10-22 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_score', models.IntegerField(default=1)),
                ('max_score', models.IntegerField(default=5)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.DecimalField(decimal_places=5, default=0, max_digits=9)),
                ('norm_score', models.DecimalField(decimal_places=5, default=0, max_digits=9)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('table', models.CharField(blank=True, max_length=15)),
                ('members', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('is_anchor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('est_time_per_demo', models.DecimalField(decimal_places=1, default=5, max_digits=3)),
                ('min_judges_per_team', models.IntegerField(default=1)),
                ('max_judges_per_sponsor_category', models.IntegerField(default=99)),
                ('time_limit', models.IntegerField(default=120)),
                ('organizers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judging.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='DemoScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judging.Criteria')),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judging.Demo')),
            ],
        ),
        migrations.AddField(
            model_name='demo',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judging.Team'),
        ),
        migrations.CreateModel(
            name='CriteriaLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judging.Criteria')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('number_winners', models.IntegerField(default=1)),
                ('min_judges', models.IntegerField(default=1, help_text='The minimum number of judges a team should be seen by for this category')),
                ('is_opt_in', models.BooleanField(default=False)),
                ('judges', models.ManyToManyField(blank=True, related_name='categories', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judging.Organization')),
                ('submissions', models.ManyToManyField(blank=True, related_name='categories', to='judging.Team')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
