# Generated by Django 2.2.6 on 2019-10-28 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterialabel',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='demoscore',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='demoscore',
            name='demo',
        ),
        migrations.AddField(
            model_name='demo',
            name='creativity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='demo',
            name='feasibility',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='demo',
            name='functionality',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='demo',
            name='impact',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='demo',
            name='ui',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
        migrations.DeleteModel(
            name='CriteriaLabel',
        ),
        migrations.DeleteModel(
            name='DemoScore',
        ),
    ]
