# Generated by Django 2.2.6 on 2019-10-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0002_auto_20191028_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
