"""empty message

Revision ID: 08d865e0fce9
Revises: 745b2e793875
Create Date: 2019-05-13 23:04:09.170896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d865e0fce9'
down_revision = '745b2e793875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'hackerid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('tickets_hackerid_fkey', 'tickets', type_='foreignkey')
    op.drop_constraint('tickets_mentorid_fkey', 'tickets', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('tickets_mentorid_fkey', 'tickets', 'hackers', ['mentorid'], ['id'])
    op.create_foreign_key('tickets_hackerid_fkey', 'tickets', 'hackers', ['hackerid'], ['id'])
    op.alter_column('tickets', 'hackerid',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
