"""empty message

Revision ID: 156576eb4c0e
Revises: 1e7a7669c918
Create Date: 2019-03-07 12:20:18.915435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156576eb4c0e'
down_revision = '1e7a7669c918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cost', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('miles', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('travel', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('travel_method', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('where_from', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'where_from')
    op.drop_column('users', 'travel_method')
    op.drop_column('users', 'travel')
    op.drop_column('users', 'miles')
    op.drop_column('users', 'cost')
    # ### end Alembic commands ###
