"""empty message

Revision ID: 1d71184a0366
Revises: 665616594b2c
Create Date: 2019-08-17 15:52:03.024730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d71184a0366'
down_revision = '665616594b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('mentors', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mentors'], ['hackers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###
