"""empty message

Revision ID: 1e7a7669c918
Revises: bb5977602c69
Create Date: 2019-03-07 11:34:43.756675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7a7669c918'
down_revision = 'bb5977602c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.String(length=1000), nullable=True))
    op.drop_column('users', 'month')
    op.drop_column('users', 'year')
    op.drop_column('users', 'day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###
