"""empty message

Revision ID: 276e550a876a
Revises: 6c316c23ece6
Create Date: 2019-08-29 18:40:34.545072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276e550a876a'
down_revision = '6c316c23ece6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    op.add_column('hackers', sa.Column('is_judge', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackers', 'is_judge')
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('mentors', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mentors'], ['hackers.id'], name='companies_mentors_fkey'),
    sa.PrimaryKeyConstraint('id', name='companies_pkey')
    )
    # ### end Alembic commands ###
