"""empty message

Revision ID: 3425c53a31f8
Revises: 
Create Date: 2019-03-06 15:57:28.776900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3425c53a31f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=1000), nullable=True),
    sa.Column('password', sa.String(length=1000), nullable=True),
    sa.Column('hash', sa.String(length=1000), nullable=True),
    sa.Column('is_hacker', sa.Boolean(), nullable=True),
    sa.Column('is_mentor', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
