"""empty message

Revision ID: 3bd90dc2dbd6
Revises: 430525330dfc
Create Date: 2019-04-23 14:09:02.752780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd90dc2dbd6'
down_revision = '430525330dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackers', sa.Column('checked_in', sa.Boolean(), nullable=True))
    op.add_column('hackers', sa.Column('qr_hash', sa.String(length=1000), nullable=True))
    op.add_column('hackers', sa.Column('sat_breakfast', sa.Boolean(), nullable=True))
    op.add_column('hackers', sa.Column('sat_dinner', sa.Boolean(), nullable=True))
    op.add_column('hackers', sa.Column('sat_lunch', sa.Boolean(), nullable=True))
    op.add_column('hackers', sa.Column('sun_breakfast', sa.Boolean(), nullable=True))
    op.add_column('hackers', sa.Column('sun_lunch', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackers', 'sun_lunch')
    op.drop_column('hackers', 'sun_breakfast')
    op.drop_column('hackers', 'sat_lunch')
    op.drop_column('hackers', 'sat_dinner')
    op.drop_column('hackers', 'sat_breakfast')
    op.drop_column('hackers', 'qr_hash')
    op.drop_column('hackers', 'checked_in')
    # ### end Alembic commands ###
