"""empty message

Revision ID: 4251ddda0e84
Revises: 4ba74d5640a6
Create Date: 2019-04-20 10:29:38.074844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4251ddda0e84'
down_revision = '4ba74d5640a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackers', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackers', 'verified')
    # ### end Alembic commands ###
