"""empty message

Revision ID: 430525330dfc
Revises: 4251ddda0e84
Create Date: 2019-04-21 23:52:22.618334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430525330dfc'
down_revision = '4251ddda0e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackers', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackers', 'is_admin')
    # ### end Alembic commands ###
