"""empty message

Revision ID: 4ba74d5640a6
Revises: c24d3cf80b74
Create Date: 2019-04-19 11:38:36.929167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba74d5640a6'
down_revision = 'c24d3cf80b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=1000), nullable=True),
    sa.Column('uuid', sa.String(length=1000), nullable=True),
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('message', sa.String(length=20000), nullable=True),
    sa.Column('action', sa.String(length=1000), nullable=True),
    sa.Column('redirect_url', sa.String(length=1000), nullable=True),
    sa.Column('sent', sa.DateTime(), nullable=True),
    sa.Column('viewed', sa.DateTime(), nullable=True),
    sa.Column('hackerid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hackerid'], ['hackers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails')
    # ### end Alembic commands ###
