"""empty message

Revision ID: 641e8f4ab54d
Revises: 
Create Date: 2019-04-04 13:15:10.816146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641e8f4ab54d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=1000), nullable=True),
    sa.Column('full_name', sa.String(length=1000), nullable=True),
    sa.Column('school', sa.String(length=1000), nullable=True),
    sa.Column('grad_year', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=100), nullable=True),
    sa.Column('race', sa.String(length=100), nullable=True),
    sa.Column('describe', sa.String(length=200), nullable=True),
    sa.Column('why', sa.String(length=1800), nullable=True),
    sa.Column('major', sa.String(length=1000), nullable=True),
    sa.Column('birthday', sa.String(length=1000), nullable=True),
    sa.Column('mlh_rules', sa.Boolean(), nullable=True),
    sa.Column('hackathons', sa.Integer(), nullable=True),
    sa.Column('app_complete', sa.Boolean(), nullable=True),
    sa.Column('travel', sa.Boolean(), nullable=True),
    sa.Column('where_from', sa.String(length=1000), nullable=True),
    sa.Column('travel_method', sa.String(length=1000), nullable=True),
    sa.Column('miles', sa.String(length=1000), nullable=True),
    sa.Column('cost', sa.String(length=1000), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=1000), nullable=True),
    sa.Column('tshirt', sa.String(length=1000), nullable=True),
    sa.Column('dietary', sa.String(length=1000), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('github', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=1000), nullable=True),
    sa.Column('password', sa.String(length=1000), nullable=True),
    sa.Column('hash', sa.String(length=1000), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('confirmation_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('confirmations')
    op.drop_table('applications')
    # ### end Alembic commands ###
