"""empty message

Revision ID: 665616594b2c
Revises: 29d13f6640f5
Create Date: 2019-05-16 19:17:11.786105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665616594b2c'
down_revision = '29d13f6640f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackers', sa.Column('company_name', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackers', 'company_name')
    # ### end Alembic commands ###
