"""empty message

Revision ID: 745b2e793875
Revises: 3bd90dc2dbd6
Create Date: 2019-05-13 23:03:07.452761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745b2e793875'
down_revision = '3bd90dc2dbd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=1000), nullable=True),
    sa.Column('question', sa.String(length=10000), nullable=True),
    sa.Column('location', sa.String(length=10000), nullable=True),
    sa.Column('contact', sa.String(length=10000), nullable=True),
    sa.Column('status', sa.String(length=1000), nullable=True),
    sa.Column('hackerid', sa.Integer(), nullable=False),
    sa.Column('mentorid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hackerid'], ['hackers.id'], ),
    sa.ForeignKeyConstraint(['mentorid'], ['hackers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hackers', sa.Column('is_mentor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackers', 'is_mentor')
    op.drop_table('tickets')
    # ### end Alembic commands ###
