"""empty message

Revision ID: 80a2ebac32f9
Revises: 276e550a876a
Create Date: 2019-08-29 18:49:08.455656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a2ebac32f9'
down_revision = '276e550a876a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackers', sa.Column('judging_password', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackers', 'judging_password')
    # ### end Alembic commands ###
