"""empty message

Revision ID: a594492031f0
Revises: 11b972685b8d
Create Date: 2019-04-15 20:43:58.438944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a594492031f0'
down_revision = '11b972685b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('rejected', sa.Boolean(), nullable=True))
    op.drop_column('applications', 'declined')
    op.add_column('confirmations', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('confirmations', sa.Column('declined', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('confirmations', 'declined')
    op.drop_column('confirmations', 'confirmed')
    op.add_column('applications', sa.Column('declined', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('applications', 'rejected')
    # ### end Alembic commands ###
