"""empty message

Revision ID: bb5977602c69
Revises: e9903a1ef4f0
Create Date: 2019-03-07 00:30:08.816614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5977602c69'
down_revision = 'e9903a1ef4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('major', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'major')
    # ### end Alembic commands ###
