"""empty message

Revision ID: c233e2171bd7
Revises: 1d71184a0366
Create Date: 2019-08-17 17:23:18.148838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c233e2171bd7'
down_revision = '1d71184a0366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackers', sa.Column('full_name', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackers', 'full_name')
    # ### end Alembic commands ###
