"""empty message

Revision ID: c24d3cf80b74
Revises: da1d5e7f6baf
Create Date: 2019-04-18 02:09:21.797586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24d3cf80b74'
down_revision = 'da1d5e7f6baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confirmations', sa.Column('hackerid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'confirmations', 'hackers', ['hackerid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'confirmations', type_='foreignkey')
    op.drop_column('confirmations', 'hackerid')
    # ### end Alembic commands ###
