"""empty message

Revision ID: e9903a1ef4f0
Revises: d01301187b79
Create Date: 2019-03-06 18:03:21.335640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9903a1ef4f0'
down_revision = 'd01301187b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('app_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'app_complete')
    # ### end Alembic commands ###
