# Generated by Django 2.2.6 on 2019-10-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
